In [7]:
import numpy as np


In [2]:
m = np.matrix('1 2 3 4; 5 6 7 8; 9 1 5 7')

In [3]:
print(m)

[[1 2 3 4]
 [5 6 7 8]
 [9 1 5 7]]


In [4]:
m = np.array(m)
type(m)

numpy.ndarray

In [5]:
len(m)

3

In [8]:
a = np.array([1, 2, 3], float)
s = a.tostring()

<ipython-input-8-aeba4e441065>:2: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  s = a.tostring()


In [9]:
s

b'\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x08@'

In [12]:
b = np.fromstring(s)

<ipython-input-12-a14abcdb0b44>:1: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  b = np.fromstring(s)


In [13]:
b

array([1., 2., 3.])

In [14]:
b.fill(0)

In [15]:
b

array([0., 0., 0.])

In [16]:
a = np.array(range(6), float).reshape((2, 3))

In [17]:
a

array([[0., 1., 2.],
       [3., 4., 5.]])

In [18]:
a.transpose()

array([[0., 3.],
       [1., 4.],
       [2., 5.]])

In [19]:
a.flatten()

array([0., 1., 2., 3., 4., 5.])

In [20]:
a = np.array([1,2], float)
b = np.array([3,4,5,6], float)
c = np.array([7,8,9], float)

In [21]:
np.concatenate((a,b,c))

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [22]:
a = np.array([[1, 2], [3, 4]], float)
b = np.array([[5, 6], [7,8]], float)

In [23]:
np.concatenate((a,b))

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [7., 8.]])

In [26]:
np.concatenate((a,b),axis = 1)

array([[1., 2., 5., 6.],
       [3., 4., 7., 8.]])

In [27]:
a = np.array([1, 2, 3], float)
a

array([1., 2., 3.])

In [28]:
a[:,np.newaxis]

array([[1.],
       [2.],
       [3.]])

In [31]:
a.shape

(3,)

In [33]:
a[np.newaxis,:]

array([[1., 2., 3.]])

In [34]:
a.shape

(3,)

In [35]:
a[np.newaxis,:].shape

(1, 3)