In [7]:
import numpy as np


In [2]:
m = np.matrix('1 2 3 4; 5 6 7 8; 9 1 5 7')

In [3]:
print(m)

[[1 2 3 4]
 [5 6 7 8]
 [9 1 5 7]]


In [4]:
m = np.array(m)
type(m)

numpy.ndarray

In [5]:
len(m)

3

In [8]:
a = np.array([1, 2, 3], float)
s = a.tostring()

<ipython-input-8-aeba4e441065>:2: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  s = a.tostring()


In [9]:
s

b'\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x08@'

In [12]:
b = np.fromstring(s)

<ipython-input-12-a14abcdb0b44>:1: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  b = np.fromstring(s)


In [13]:
b

array([1., 2., 3.])

In [14]:
b.fill(0)

In [15]:
b

array([0., 0., 0.])

In [16]:
a = np.array(range(6), float).reshape((2, 3))

In [17]:
a

array([[0., 1., 2.],
       [3., 4., 5.]])

In [18]:
a.transpose()

array([[0., 3.],
       [1., 4.],
       [2., 5.]])

In [19]:
a.flatten()

array([0., 1., 2., 3., 4., 5.])

In [20]:
a = np.array([1,2], float)
b = np.array([3,4,5,6], float)
c = np.array([7,8,9], float)

In [21]:
np.concatenate((a,b,c))

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [22]:
a = np.array([[1, 2], [3, 4]], float)
b = np.array([[5, 6], [7,8]], float)

In [23]:
np.concatenate((a,b))

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [7., 8.]])

In [26]:
np.concatenate((a,b),axis = 1)

array([[1., 2., 5., 6.],
       [3., 4., 7., 8.]])

In [27]:
a = np.array([1, 2, 3], float)
a

array([1., 2., 3.])

In [28]:
a[:,np.newaxis]

array([[1.],
       [2.],
       [3.]])

In [31]:
a.shape

(3,)

In [33]:
a[np.newaxis,:]

array([[1., 2., 3.]])

In [34]:
a.shape

(3,)

In [35]:
a[np.newaxis,:].shape

(1, 3)

In [17]:
np.arange(5,dtype = float)

array([0., 1., 2., 3., 4.])

In [18]:
np.ones((3,3),dtype = float)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [20]:
np.zeros((2,4),dtype = int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [21]:
aha = np.array([[1, 2, 3], [4, 5, 6]], float)

In [22]:
aha

array([[1., 2., 3.],
       [4., 5., 6.]])

In [23]:
np.zeros_like(aha)

array([[0., 0., 0.],
       [0., 0., 0.]])

In [24]:
import numpy as np
import pandas as pd
df = pd.DataFrame()
x = df.values
type(x)

numpy.ndarray

In [29]:
import numpy as np
import pandas as pd
my_series = pd.Series([5, 6, 7, 8, 9, 10])
my_series.values


array([ 5,  6,  7,  8,  9, 10])

In [30]:
np.empty(5)

array([0., 1., 2., 3., 4.])

In [31]:
np.ones((3,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [32]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
np.full((3, 5), 3.14123) 

array([[3.14123, 3.14123, 3.14123, 3.14123, 3.14123],
       [3.14123, 3.14123, 3.14123, 3.14123, 3.14123],
       [3.14123, 3.14123, 3.14123, 3.14123, 3.14123]])

In [34]:
np.arange(0, 21, 7)

array([ 0,  7, 14])

In [35]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [36]:
np.random.randint(0, 10, (3, 3)) 

array([[9, 2, 6],
       [7, 6, 0],
       [1, 7, 2]])

In [39]:
np.random.randint(0, 100, (3, 3)) 

array([[50, 38, 77],
       [31,  1, 62],
       [11, 76, 24]])

In [40]:
my_secret = [x for x in range(1, 301, 7) if x%10 == 7 or x%10 == 1]
np.array([my_secret, [x/2 for x in my_secret], [x-100 for x in my_secret]])

array([[  1. ,  57. ,  71. , 127. , 141. , 197. , 211. , 267. , 281. ],
       [  0.5,  28.5,  35.5,  63.5,  70.5,  98.5, 105.5, 133.5, 140.5],
       [-99. , -43. , -29. ,  27. ,  41. ,  97. , 111. , 167. , 181. ]])

In [48]:
np.random.randint(0, 4, (3, 3)) 

array([[3, 2, 1],
       [3, 1, 1],
       [3, 1, 2]])

In [49]:
np.arange(1, 14, 2) 

array([ 1,  3,  5,  7,  9, 11, 13])

In [50]:
np.array(range(9)) 

array([0, 1, 2, 3, 4, 5, 6, 7, 8])